# Generated by Django 4.2.11 on 2024-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactform_remove_car_image_watchlistitem_testdrive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='car/')),
            ],
        ),
    ]
