# Generated by Django 4.2.11 on 2024-08-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='car/')),
                ('battery_capacity', models.FloatField(help_text='Battery capacity in kWh')),
                ('range', models.FloatField(help_text='Range in miles')),
                ('horsepower', models.IntegerField(help_text='Horsepower in HP')),
                ('transmission', models.CharField(help_text='Transmission type', max_length=50)),
                ('dimensions', models.CharField(help_text='Dimensions (e.g., LxWxH in inches)', max_length=100)),
                ('weight', models.FloatField(help_text='Weight in lbs')),
                ('seating_capacity', models.IntegerField(help_text='Seating capacity in seats')),
                ('drive_type', models.CharField(help_text='Drive type (e.g., AWD, FWD, RWD)', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='EvCar',
        ),
    ]
