# Generated by Django 4.2.11 on 2024-08-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ecar_delete_evcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('economy', 'Economy'), ('compact', 'Compact'), ('massive', 'Massive'), ('suv', 'SUV'), ('standard', 'Standard')], max_length=20)),
                ('passengers', models.CharField(choices=[('1-2', '1-2 Passengers'), ('3-5', '3-5 Passengers'), ('6_or_more', '6 or More Passengers')], max_length=20)),
                ('bags', models.CharField(choices=[('1-2', '1-2 Bags'), ('3-5', '3-5 Bags'), ('6_or_more', '6 or More Bags')], max_length=20)),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
            ],
        ),
    ]
